# Generated by Django 6.0.5 on 2026-05-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venue_happyhour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happyhour',
            name='day_of_week',
            field=models.CharField(max_length=50),
        ),
    ]
