# Generated by Django 6.0.5 on 2026-05-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_alter_happyhour_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happyhour',
            name='day_of_week',
            field=models.TextField(),
        ),
    ]
